// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortalHub.Models;

#nullable disable

namespace PortalHub.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    [Migration("20240308203520_CreateTables")]
    partial class CreateTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PortalHub.Areas.Management.Models.Lucerna_KPI", b =>
                {
                    b.Property<int>("ID_LOG")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_LOG");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_LOG"));

                    b.Property<DateTime>("DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATE");

                    b.Property<int>("EMPLOYEE_NO")
                        .HasColumnType("int")
                        .HasColumnName("EMPLOYEE_NO");

                    b.Property<int>("ID_IND1")
                        .HasColumnType("int")
                        .HasColumnName("ID_IND1");

                    b.Property<DateTime>("IND_DATE")
                        .HasColumnType("datetime2")
                        .HasColumnName("IND_DATE");

                    b.Property<int>("QUANTITY")
                        .HasColumnType("int")
                        .HasColumnName("QUANTITY");

                    b.HasKey("ID_LOG");

                    b.ToTable("IND_LOG", (string)null);
                });

            modelBuilder.Entity("PortalHub.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CompanyKey")
                        .HasColumnType("int")
                        .HasColumnName("COMPANY_KEY");

                    b.Property<int?>("DepartmentNo")
                        .HasColumnType("int")
                        .HasColumnName("DEPARTMENT_NO");

                    b.Property<string>("Email")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("EMAIL");

                    b.Property<bool?>("EmailConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("EMAIL_CONFIRMED");

                    b.Property<int>("EmployeeNo")
                        .HasMaxLength(20)
                        .HasColumnType("int")
                        .HasColumnName("EMPLOYEE_NO");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IS_ACTIVE");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("NAME");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("PHONE_NUMBER");

                    b.Property<bool?>("PhoneNumberConfirmed")
                        .HasColumnType("bit")
                        .HasColumnName("PHONE_NUMBER_CONFIRMED");

                    b.Property<int?>("PictureId")
                        .HasColumnType("int")
                        .HasColumnName("PICTURE_ID");

                    b.Property<int?>("PositionKey")
                        .HasColumnType("int")
                        .HasColumnName("POSITION_KEY");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SECURITY_STAMP");

                    b.Property<string>("UserName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.ToTable("USERS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
